server:
  port: 8602
spring:
  application:
    name: eureka-server2
eureka:
#  instance:
#    hostname: eurekaserver2
  client:
    serviceUrl:
      # 设置服务注册中心地址，指向另一个注册中心，使用域名作为访问路径
      defaultZone: http://localhost:8601/eureka/
    register-with-eureka: false
